### ISSUE TITLE
diversity & open source history curriculum - a few resources

### ISSUE THREAD

**Issue by brainwane** [mozilla/inclusion#229]
## Objective Goal: 
I'd like for you to consider using these documents as you develop a curriculum on the history of diversity in open source.

## Related documents and links 
* [history of Outreachy](https://www.harihareswara.net/sumana/2015/03/05/0)
* [Where are the women in the history of open source?](http://crookedtimber.org/2015/05/21/where-are-the-women-in-the-history-of-open-source/)
* [What if free and open source software were more like fandom?](https://geekfeminismdotorg.wordpress.com/2015/05/22/what-if-open-source-were-more-like-fandom/)

**Comment by emmairwin** [comment]
Thank you @brainwane I will, absolutely.

**Comment by Dmitriy11111** [comment]
> ## Objective Goal: 
> 
> I'd like for you to consider using these documents as you develop a curriculum on the history of diversity in open source.
> 
> 
> 
> ## Related documents and links 
> 
> * [history of Outreachy](https://www.harihareswara.net/sumana/2015/03/05/0)
> 
> * [Where are the women in the history of open source?](http://crookedtimber.org/2015/05/21/where-are-the-women-in-the-history-of-open-source/)
> 
> * [What if free and open source software were more like fandom?](https://geekfeminismdotorg.wordpress.com/2015/05/22/what-if-open-source-were-more-like-fandom/)
> 
> 
> 
>

**Comment by TenebrisVulpes** [comment]
> ## Objective Goal: 
> 
> I'd like for you to consider using these documents as you develop a curriculum on the history of diversity in open source.
> 
> 
> 
> ## Related documents and links 
> 
> * [history of Outreachy](https://www.harihareswara.net/sumana/2015/03/05/0)
> 
> * [Where are the women in the history of open source?](http://crookedtimber.org/2015/05/21/where-are-the-women-in-the-history-of-open-source/)
> 
> * [What if free and open source software were more like fandom?](https://geekfeminismdotorg.wordpress.com/2015/05/22/what-if-open-source-were-more-like-fandom/)
> 
> 
> 
>

**Comment by emmairwin** [comment]
^ Spam

**Comment by couci** [comment]
Closing as suggested by @emmairwin
