### ISSUE TITLE
Adds functionality to add files to an existing gist. Add files with absolute path, relative path, files present in the current working directory and new files from stdin.

### ISSUE THREAD

**Issue by TenebrisVulpes** [mozilla/inclusion#264]
Adds functionality to add files to an existing gist. Add files with absolute path, relative path, files present in the current working directory and new files from stdin.

Closes #2903 

__Originally posted by @g14a in https://github.com/cli/cli/pull/2997__

**Comment by couci** [comment]
This is not related to mozilla's inclusion work, closing
