### ISSUE TITLE
Thanks for opening this!

### ISSUE THREAD

**Issue by TenebrisVulpes** [mozilla/inclusion#265]
Thanks for opening this!

I'd like this work to be adding a new flag to `gh edit` called `--add`; eg:

```
gh gist edit ee6ed8a783e4fef5b69b2ed42d743b1a -a "foo.txt"
```

that can be invoked multiple times to add files to a gist.

Assigning this to @g14a . Let me know if you have questions on the implementation.

__Originally posted by @vilmibm in https://github.com/cli/cli/issues/2903#issuecomment-780149260__

**Comment by couci** [comment]
This is not related to mozilla's inclusion work, closing
