### ISSUE TITLE
You know the drill!

### ISSUE THREAD

**Issue by TenebrisVulpes** [mozilla/inclusion#267]
You know the drill!

When you get a chance, open a PR on your personal and team building goals for **Aug, Sept, Oct**. Remember to:

- Follow the [Objectives and Key Results format](https://en.wikipedia.org/wiki/OKR)
- Focus on your strengths. 
- Focus on aligning our team goals with your long-term goals as much as possible.

Let's use the following format:

### Technical Development Goals -- Include 2 or 3 projects or tasks you plan to work on that:

- Align with your team's roadmap. 
- Include what steps you are planning to take to make sure you and others in the team can complete our goals.  
- A time by which you target completion date of each of your goals.

### Personal Development Goals -- Include 2 or 3 actions you plan to take to: 

- Build relationships with other members of our team and beyond.
- Demonstrate your technical and project leadership skills. 
- Actions you are planning to take to make your teammates feel happier and be more successful.
- Your learning plan actions to get yourself ready to take on the work that’s planned for the second half of 2018.
- A time by which you target completion date of each of your goals.

Please try to have your first draft of these ready for our next 1:1. We can then discuss and :ship: them :smile:.

__Originally posted by @juliamae in https://github.com/vilmibm/vilmibm/issues/3__

**Comment by couci** [comment]
This is not related to mozilla's inclusion work, closing
